import './modules/animation'
import './modules/application'
import './modules/catalog-filter'
import './modules/dropdown'
import './modules/mobile-menu'
import './modules/number-mask'
import './modules/swiper'
import './modules/video'
